export enum StoreTypes {
  INCREASE_STOCK = 'INCREASE_STOCK',
  DECREASE_STOCK = 'DECREASE_STOCK',
  DISABLE_PRODUCT = 'DISABLE_PRODUCT',
  ADD_STORE_ITEM = 'ADD_STORE_ITEM',
  REMOVE_STORE_ITEM = 'REMOVE_STORE_ITEM',
  INCREMENT_INDEX = 'INCREMENT_INDEX',
  GET_DEPLOYED_STORE = 'GET_DEPLOYED_STORE',
  RECEIVE_ITEMS = 'RECEIVE_ITEMS',
  REQUEST_ITEMS = 'REQUEST_ITEMS',
  GET_ITEM = 'GET_ITEM',
  NEW_STORE = 'NEW_STORE',
}
