export const INCREASE_STOCK = 'INCREASE_STOCK';
export const DECREASE_STOCK = 'DECREASE_STOCK';
export const DISABLE_PRODUCT = 'DISABLE_PRODUCT';
export const ADD_STORE_ITEM = 'ADD_STORE_ITEM';
export const REMOVE_STORE_ITEM = 'REMOVE_STORE_ITEM';
