export enum StoreTypes {
  INCREASE_STOCK = 'INCREASE_STOCK',
  DECREASE_STOCK = 'DECREASE_STOCK',
  DISABLE_PRODUCT = 'DISABLE_PRODUCT',
  ADD_STORE_ITEM = 'ADD_STORE_ITEM',
  REMOVE_STORE_ITEM = 'REMOVE_STORE_ITEM',
  SHOW_MODAL = 'SHOW_MODAL',
  ADD_MODAL = 'ADD_MODAL'
}
