export enum Web3Types {
  CREATE_INSTANCE = 'CREATE_INSTANCE',
  SET_PROVIDER = 'SET_PROVIDER',
  DEPLOY_STORE = 'DEPLOY_STORE',
  GET_DEPLOYED_STORE = 'GET_DEPLOYED_STORE',
  RECEIVE_ITEMS = 'RECEIVE_ITEMS',
}
